name: 🎎 Haiku detection
description: Detects if an issue contains a haiku
inputs:
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    - name: 💾 Install dependencies
      run: npm install syllable
      shell: bash
    - name: 👺 Check for haiku
      run: node ./.github/actions/haiku/haiku.js
      shell: bash
